# Generated by Django 6.0.7 on 2026-07-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighFiScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(upload_to='prototypes/high-fi/extra/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Additional Screenshot',
                'verbose_name_plural': 'Additional Screenshots',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LowFidelityPrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_sw', models.CharField(blank=True, max_length=200, verbose_name='Title (Swahili)')),
                ('page_name', models.CharField(help_text='e.g., Home Page, Login Screen, Dashboard', max_length=100, verbose_name='Page/Screen Name')),
                ('description', models.TextField(help_text='Explain the sketch, what it represents, and design decisions', verbose_name='Description')),
                ('description_sw', models.TextField(blank=True, verbose_name='Description (Swahili)')),
                ('sketch_image', models.ImageField(help_text='Upload clear photo/scan of hand sketch', upload_to='prototypes/low-fi/', verbose_name='Sketch Image')),
                ('design_rationale', models.TextField(blank=True, help_text='Why this design approach was chosen', verbose_name='Design Rationale')),
                ('user_interactions', models.TextField(blank=True, help_text='Describe how users will interact with this screen', verbose_name='User Interactions')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Low-Fidelity Prototype',
                'verbose_name_plural': 'Low-Fidelity Prototypes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MediumFidelityPrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_sw', models.CharField(blank=True, max_length=200, verbose_name='Title (Swahili)')),
                ('page_name', models.CharField(max_length=100, verbose_name='Page/Screen Name')),
                ('description', models.TextField(help_text='Describe the wireframe and its functionality', verbose_name='Description')),
                ('description_sw', models.TextField(blank=True, verbose_name='Description (Swahili)')),
                ('wireframe_image', models.ImageField(upload_to='prototypes/med-fi/', verbose_name='Wireframe Image')),
                ('navigation_flow', models.TextField(help_text='Describe how users navigate to and from this screen', verbose_name='Navigation Flow')),
                ('improvements_from_lowfi', models.TextField(help_text='What changed from the paper sketches and why', verbose_name='Improvements from Low-Fidelity')),
                ('improvements_from_lowfi_sw', models.TextField(blank=True, verbose_name='Improvements from Low-Fidelity (Swahili)')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_screens', models.ManyToManyField(blank=True, help_text='Other screens this wireframe links to', to='prototypes.mediumfidelityprototype', verbose_name='Connected Screens')),
                ('lowfi_reference', models.ForeignKey(blank=True, help_text='Link to the original low-fidelity sketch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediumfi_versions', to='prototypes.lowfidelityprototype', verbose_name='Low-Fi Reference')),
            ],
            options={
                'verbose_name': 'Medium-Fidelity Prototype',
                'verbose_name_plural': 'Medium-Fidelity Prototypes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HighFidelityPrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_sw', models.CharField(blank=True, max_length=200, verbose_name='Title (Swahili)')),
                ('page_name', models.CharField(max_length=100, verbose_name='Page/Screen Name')),
                ('screen_type', models.CharField(choices=[('home', 'Home Page'), ('dashboard', 'Dashboard'), ('login', 'Login/Register'), ('profile', 'User Profile'), ('list', 'List View'), ('detail', 'Detail View'), ('form', 'Form/Input'), ('settings', 'Settings'), ('other', 'Other')], default='other', max_length=20, verbose_name='Screen Type')),
                ('description', models.TextField(help_text='Detailed explanation of this screen', verbose_name='Description')),
                ('description_sw', models.TextField(blank=True, verbose_name='Description (Swahili)')),
                ('screenshot', models.ImageField(upload_to='prototypes/high-fi/', verbose_name='Screenshot')),
                ('color_palette', models.TextField(blank=True, help_text='Hex codes and color usage', verbose_name='Color Palette')),
                ('typography', models.TextField(blank=True, help_text='Fonts, sizes, and usage', verbose_name='Typography')),
                ('interaction_details', models.TextField(blank=True, help_text='Animations, transitions, micro-interactions', verbose_name='Interaction Details')),
                ('design_system_notes', models.TextField(blank=True, help_text='Components, patterns, and design decisions', verbose_name='Design System Notes')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_screenshots', models.ManyToManyField(blank=True, related_name='highfi_prototypes', to='prototypes.highfiscreenshot')),
                ('medfi_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highfi_versions', to='prototypes.mediumfidelityprototype', verbose_name='Med-Fi Reference')),
            ],
            options={
                'verbose_name': 'High-Fidelity Prototype',
                'verbose_name_plural': 'High-Fidelity Prototypes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DesignIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Change Title')),
                ('description', models.TextField(verbose_name='What Changed')),
                ('reason', models.TextField(verbose_name='Why It Changed')),
                ('before_image', models.ImageField(upload_to='prototypes/iterations/before/', verbose_name='Before Screenshot')),
                ('after_image', models.ImageField(upload_to='prototypes/iterations/after/', verbose_name='After Screenshot')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highfi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prototypes.highfidelityprototype')),
                ('lowfi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prototypes.lowfidelityprototype')),
                ('mediumfi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prototypes.mediumfidelityprototype')),
            ],
            options={
                'verbose_name': 'Design Iteration',
                'verbose_name_plural': 'Design Iterations',
                'ordering': ['order'],
            },
        ),
    ]
