# Generated by Django 6.0.7 on 2026-07-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('project_name', models.CharField(default='HCI Design Portfolio', max_length=200, verbose_name='Project Name')),
                ('project_tagline', models.CharField(default='Human-Computer Interface Design Journey', max_length=500, verbose_name='Project Tagline')),
                ('programme_name', models.CharField(default='Bachelor of Computer Science', max_length=200, verbose_name='Programme Name')),
                ('course_code', models.CharField(default='CSU07425/ITUO7425', max_length=20, verbose_name='Course Code')),
                ('university_name', models.CharField(default='The Institute of Finance Management', max_length=200, verbose_name='University Name')),
                ('faculty_name', models.CharField(default='Faculty of Computing, Information Systems and Mathematics', max_length=200, verbose_name='Faculty Name')),
                ('department_name', models.CharField(default='Department of Information Technology', max_length=200, verbose_name='Department Name')),
                ('logo', models.ImageField(blank=True, help_text='Recommended size: 200x60px. PNG or SVG preferred.', upload_to='branding/', verbose_name='Site Logo')),
                ('favicon', models.ImageField(blank=True, help_text='32x32px ICO or PNG file.', upload_to='branding/', verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#1a237e', help_text='Hex color code (e.g., #1a237e)', max_length=7, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#1976d2', help_text='Hex color code (e.g., #1976d2)', max_length=7, verbose_name='Secondary Color')),
                ('project_description', models.TextField(blank=True, help_text='2-3 sentence compelling description of your project.', verbose_name='Project Description')),
                ('problem_statement', models.TextField(blank=True, help_text='What problem does your project solve?', verbose_name='Problem Statement')),
                ('target_users', models.TextField(blank=True, help_text='Who are the primary users of your system?', verbose_name='Target Users')),
                ('system_overview', models.TextField(blank=True, help_text='Brief overview of the system functionality.', verbose_name='System Overview')),
                ('objectives', models.TextField(blank=True, help_text='What are the main objectives of this project?', verbose_name='Project Objectives')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('registration_number', models.CharField(help_text='Student registration number (e.g., CSU/2024/001)', max_length=20, unique=True, verbose_name='Registration Number')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('PM', 'Project Manager - Coordination & Scheduling'), ('PR', 'Presenter - Creates & Delivers Presentations'), ('EV', 'Evaluator - Performs & Documents Evaluations'), ('CO', 'Coder - Develops Prototypes & Code'), ('DE', 'Designer - Low & Medium Fidelity Prototypes'), ('RE', 'Researcher - Research Other Similar Systems')], default='PM', help_text='Select the team member role from the dropdown', max_length=2, verbose_name='Role')),
                ('contribution', models.TextField(help_text='Describe what this member contributed to the project.', verbose_name='Contribution')),
                ('bio', models.TextField(blank=True, help_text='Short professional biography (optional).', verbose_name='Biography')),
                ('photo', models.ImageField(blank=True, help_text='Professional headshot (optional). Recommended: 400x400px.', upload_to='team/photos/', verbose_name='Photo')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Use 0, 1, 2, 3...', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this member on the website.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'last_name', 'first_name'],
            },
        ),
    ]
