# Generated by Django 6.0.7 on 2026-07-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='faculty_name',
            field=models.CharField(default='Faculty of Computing and Mathematics', max_length=200, verbose_name='Faculty Name'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='programme_name',
            field=models.CharField(default='Bachelor of  Science in information Technology', max_length=200, verbose_name='Programme Name'),
        ),
    ]
