# Generated by Django 6.0.7 on 2026-07-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_sw', models.CharField(blank=True, max_length=200, verbose_name='Title (Swahili)')),
                ('code', models.CharField(help_text='e.g., FR-001, FR-002', max_length=20, unique=True, verbose_name='Requirement Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_sw', models.TextField(blank=True, verbose_name='Description (Swahili)')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('implemented', 'Implemented'), ('in_progress', 'In Progress'), ('planned', 'Planned')], default='planned', max_length=20, verbose_name='Status')),
                ('category', models.CharField(help_text='e.g., User Management, Authentication, Reporting', max_length=100, verbose_name='Category')),
                ('icon', models.CharField(default='fas fa-check-circle', help_text='Font Awesome icon class', max_length=50, verbose_name='Icon')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Functional Requirement',
                'verbose_name_plural': 'Functional Requirements',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='NonFunctionalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_sw', models.CharField(blank=True, max_length=200, verbose_name='Title (Swahili)')),
                ('code', models.CharField(help_text='e.g., NFR-001, UR-001', max_length=20, unique=True, verbose_name='Requirement Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_sw', models.TextField(blank=True, verbose_name='Description (Swahili)')),
                ('category', models.CharField(choices=[('usability', 'Usability'), ('performance', 'Performance'), ('security', 'Security'), ('reliability', 'Reliability'), ('maintainability', 'Maintainability'), ('compatibility', 'Compatibility')], max_length=20, verbose_name='Category')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='Priority')),
                ('icon', models.CharField(default='fas fa-shield-alt', help_text='Font Awesome icon class', max_length=50, verbose_name='Icon')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Non-Functional Requirement',
                'verbose_name_plural': 'Non-Functional Requirements',
                'ordering': ['category', 'order'],
            },
        ),
    ]
