# Generated by Django 6.0.7 on 2026-07-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heuristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Heuristic Number')),
                ('name', models.CharField(max_length=200, verbose_name='Heuristic Name')),
                ('name_sw', models.CharField(blank=True, max_length=200, verbose_name='Heuristic Name (Swahili)')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_sw', models.TextField(blank=True, verbose_name='Description (Swahili)')),
            ],
            options={
                'verbose_name': 'Heuristic',
                'verbose_name_plural': 'Heuristics',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='HeuristicEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Evaluation Title')),
                ('method', models.CharField(choices=[('heuristic', "Nielsen's Heuristic Evaluation"), ('cognitive', 'Cognitive Walkthrough'), ('think_aloud', 'Think Aloud Protocol'), ('expert_review', 'Expert Review')], default='heuristic', max_length=20, verbose_name='Evaluation Method')),
                ('date_conducted', models.DateField(verbose_name='Date Conducted')),
                ('evaluators', models.TextField(help_text='Names and roles of evaluators, one per line', verbose_name='Evaluators')),
                ('number_of_evaluators', models.IntegerField(default=3, verbose_name='Number of Evaluators')),
                ('prototype_evaluated', models.CharField(help_text='Which prototype version was evaluated?', max_length=200, verbose_name='Prototype Evaluated')),
                ('session_duration', models.CharField(help_text='e.g., 2 hours, 1 day', max_length=50, verbose_name='Session Duration')),
                ('total_problems_found', models.IntegerField(default=0)),
                ('summary', models.TextField(help_text='Overall findings and recommendations', verbose_name='Evaluation Summary')),
                ('summary_sw', models.TextField(blank=True, verbose_name='Evaluation Summary (Swahili)')),
                ('full_report_link', models.URLField(blank=True, help_text='Link to detailed evaluation report (Google Docs, PDF, etc.)', verbose_name='Full Report Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Heuristic Evaluation',
                'verbose_name_plural': 'Heuristic Evaluations',
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Poster Title')),
                ('title_sw', models.CharField(blank=True, max_length=200, verbose_name='Poster Title (Swahili)')),
                ('poster_image', models.ImageField(upload_to='posters/', verbose_name='Poster Image')),
                ('description', models.TextField(help_text='Brief description of the poster content', verbose_name='Description')),
                ('description_sw', models.TextField(blank=True, verbose_name='Description (Swahili)')),
                ('problem_summary', models.TextField(blank=True, verbose_name='Problem Summary')),
                ('solution_summary', models.TextField(blank=True, verbose_name='Solution Summary')),
                ('methodology_summary', models.TextField(blank=True, verbose_name='Methodology Summary')),
                ('key_features', models.TextField(blank=True, verbose_name='Key Features')),
                ('results_summary', models.TextField(blank=True, verbose_name='Results Summary')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Poster',
                'verbose_name_plural': 'Posters',
            },
        ),
        migrations.CreateModel(
            name='EvaluationFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.CharField(max_length=200, verbose_name='Problem Title')),
                ('problem_description', models.TextField(help_text='Detailed description of the usability problem', verbose_name='Problem Description')),
                ('problem_description_sw', models.TextField(blank=True, verbose_name='Problem Description (Swahili)')),
                ('screen_location', models.CharField(help_text='Where in the interface was the problem found?', max_length=200, verbose_name='Screen/Page Location')),
                ('severity', models.CharField(choices=[('cosmetic', '0 - Cosmetic (No fix needed)'), ('minor', '1 - Minor (Fix if time)'), ('major', '2 - Major (Important to fix)'), ('catastrophic', '3 - Catastrophic (Must fix)')], default='minor', max_length=15, verbose_name='Severity Rating')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('fixed', 'Fixed'), ('wont_fix', "Won't Fix")], default='open', max_length=15, verbose_name='Status')),
                ('before_screenshot', models.ImageField(help_text='Screenshot showing the problem', upload_to='evaluations/before/', verbose_name='Before Screenshot')),
                ('after_screenshot', models.ImageField(help_text='Screenshot showing the fix', upload_to='evaluations/after/', verbose_name='After Screenshot')),
                ('recommendation', models.TextField(help_text='How to fix the problem', verbose_name='Recommendation')),
                ('changes_made', models.TextField(help_text='What was actually changed', verbose_name='Changes Made')),
                ('why_changes_were_made', models.TextField(help_text='Justification for the design changes', verbose_name='Why Changes Were Made')),
                ('discovered_by', models.CharField(help_text='Which evaluator found this issue?', max_length=200, verbose_name='Discovered By')),
                ('finding_number', models.IntegerField(default=0, verbose_name='Finding Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heuristic_violated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations.heuristic', verbose_name='Heuristic Violated')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='evaluations.heuristicevaluation', verbose_name='Evaluation Session')),
            ],
            options={
                'verbose_name': 'Evaluation Finding',
                'verbose_name_plural': 'Evaluation Findings',
                'ordering': ['severity', 'finding_number'],
            },
        ),
    ]
