# Generated by Django 6.0.7 on 2026-07-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Registration Number')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('project_manager', 'Project Manager'), ('designer', 'Designer'), ('evaluator', 'Evaluator'), ('coder', 'Coder'), ('researcher', 'Researcher'), ('presenter', 'Presenter')], max_length=20, verbose_name='Role')),
                ('role_description', models.TextField(blank=True, help_text='Detailed description of responsibilities', verbose_name='Role Description')),
                ('contribution', models.TextField(help_text='Specific contributions to the project', verbose_name='Contribution')),
                ('photo', models.ImageField(blank=True, help_text='Professional headshot or photo', upload_to='team/photos/', verbose_name='Photo')),
                ('bio', models.TextField(blank=True, help_text='Short professional bio', verbose_name='Biography')),
                ('skills', models.TextField(blank=True, help_text='Relevant skills for HCI, comma separated', verbose_name='Skills')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Member')),
                ('is_leader', models.BooleanField(default=False, verbose_name='Team Leader')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'last_name'],
            },
        ),
    ]
