# Generated by Django 6.0.7 on 2026-07-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='HCI Portfolio', max_length=200, verbose_name='Project Name')),
                ('project_name_sw', models.CharField(default='Kwingiko la HCI', max_length=200, verbose_name='Project Name (Swahili)')),
                ('logo_dark', models.ImageField(help_text='Logo for dark mode', upload_to='logo/', verbose_name='Logo (Dark Theme)')),
                ('logo_light', models.ImageField(help_text='Logo for light mode', upload_to='logo/', verbose_name='Logo (Light Theme)')),
                ('favicon', models.ImageField(upload_to='logo/', verbose_name='Favicon')),
                ('hero_title', models.CharField(default='Human Computer Interface Design', max_length=200, verbose_name='Hero Title')),
                ('hero_title_sw', models.CharField(default='Usanifu wa Kiolesura cha Kompyuta na Binadamu', max_length=200, verbose_name='Hero Title (Swahili)')),
                ('hero_subtitle', models.CharField(default='A User-Centered Design Case Study', max_length=200, verbose_name='Hero Subtitle')),
                ('hero_subtitle_sw', models.CharField(default='Uchunguzi wa Usanifu unaomlenga Mtumiaji', max_length=200, verbose_name='Hero Subtitle (Swahili)')),
                ('brief_intro', models.TextField(help_text='2-3 sentences describing the project', verbose_name='Brief Introduction')),
                ('brief_intro_sw', models.TextField(blank=True, verbose_name='Brief Introduction (Swahili)')),
                ('problem_statement', models.TextField(help_text='What problem does this project solve?', verbose_name='Problem Statement')),
                ('problem_statement_sw', models.TextField(blank=True, verbose_name='Problem Statement (Swahili)')),
                ('target_users', models.TextField(help_text='Who are the intended users?', verbose_name='Target Users')),
                ('target_users_sw', models.TextField(blank=True, verbose_name='Target Users (Swahili)')),
                ('programme', models.CharField(default='BSc. Computer Science / BSc. Information Technology', max_length=200, verbose_name='Programme')),
                ('course_code', models.CharField(default='CSU07425/ITUO7425', max_length=50, verbose_name='Course Code')),
                ('university', models.CharField(default='Institute of Finance Management', max_length=200, verbose_name='University')),
                ('faculty', models.CharField(default='Faculty of Computing, Information Systems and Mathematics', max_length=200, verbose_name='Faculty')),
                ('footer_text', models.CharField(default='© 2026 HCI Portfolio - IFM. All rights reserved.', max_length=200, verbose_name='Footer Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='ProjectObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Objective')),
                ('title_sw', models.CharField(blank=True, max_length=200, verbose_name='Objective (Swahili)')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_sw', models.TextField(blank=True, verbose_name='Description (Swahili)')),
                ('icon', models.CharField(default='fas fa-bullseye', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('site_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='pages.sitesetting')),
            ],
            options={
                'verbose_name': 'Project Objective',
                'verbose_name_plural': 'Project Objectives',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Section Title')),
                ('title_sw', models.CharField(blank=True, max_length=200, verbose_name='Section Title (Swahili)')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_sw', models.TextField(blank=True, verbose_name='Content (Swahili)')),
                ('icon', models.CharField(default='fas fa-info-circle', help_text='Font Awesome icon class', max_length=50)),
                ('section_type', models.CharField(choices=[('overview', 'System Overview'), ('why_exists', 'Why Project Exists'), ('objectives', 'Objectives'), ('users', 'Users')], max_length=50, verbose_name='Section Type')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('site_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_sections', to='pages.sitesetting')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='User Group Name')),
                ('name_sw', models.CharField(blank=True, max_length=200, verbose_name='User Group Name (Swahili)')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_sw', models.TextField(blank=True, verbose_name='Description (Swahili)')),
                ('icon', models.CharField(default='fas fa-users', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('site_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='pages.sitesetting')),
            ],
            options={
                'verbose_name': 'User Group',
                'verbose_name_plural': 'User Groups',
                'ordering': ['order'],
            },
        ),
    ]
