# Generated by Django 6.0.7 on 2026-07-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Problem Title')),
                ('description', models.TextField(verbose_name='Problem Description')),
                ('description_sw', models.TextField(blank=True, verbose_name='Problem Description (Swahili)')),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='Severity')),
                ('affected_users', models.CharField(max_length=200, verbose_name='Affected Users')),
                ('evidence', models.TextField(help_text='How was this problem discovered?', verbose_name='Evidence')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Problem Found',
                'verbose_name_plural': 'Problems Found',
                'ordering': ['severity', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ResearchFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Finding')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_sw', models.TextField(blank=True, verbose_name='Description (Swahili)')),
                ('implication', models.TextField(help_text='How this finding affects our design decisions', verbose_name='Design Implication')),
                ('icon', models.CharField(default='fas fa-search', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Research Finding',
                'verbose_name_plural': 'Research Findings',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResearchScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(upload_to='research/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Research Screenshot',
                'verbose_name_plural': 'Research Screenshots',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Opportunity Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_sw', models.TextField(blank=True, verbose_name='Description (Swahili)')),
                ('how_to_address', models.TextField(help_text='How our system will address this opportunity', verbose_name='How to Address')),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=10)),
                ('icon', models.CharField(default='fas fa-lightbulb', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('related_problems', models.ManyToManyField(blank=True, related_name='opportunities', to='research.problemfound')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['priority', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='System Name')),
                ('developer', models.CharField(blank=True, max_length=200, verbose_name='Developer/Company')),
                ('website_url', models.URLField(blank=True, verbose_name='Website URL')),
                ('system_type', models.CharField(choices=[('direct', 'Direct Competitor'), ('indirect', 'Indirect Competitor'), ('inspiration', 'Inspiration Source')], default='direct', max_length=20, verbose_name='System Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('features', models.TextField(verbose_name='Key Features')),
                ('strengths', models.TextField(verbose_name='Strengths')),
                ('weaknesses', models.TextField(verbose_name='Weaknesses')),
                ('ui_analysis', models.TextField(help_text='Analysis of interface design, usability, and user experience', verbose_name='UI/UX Analysis')),
                ('design_patterns_used', models.TextField(blank=True, help_text='UI patterns, navigation styles, interaction methods', verbose_name='Design Patterns Used')),
                ('screenshot', models.ImageField(upload_to='research/screenshots/', verbose_name='Screenshot')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_screenshots', models.ManyToManyField(blank=True, related_name='competitor_systems', to='research.researchscreenshot')),
            ],
            options={
                'verbose_name': 'Competitor System',
                'verbose_name_plural': 'Competitor Systems',
                'ordering': ['order', 'name'],
            },
        ),
    ]
